search_phrases = [
    'aspiring human resources',
    'human resources assistant',
    'hr coordinator',
    'hr generalist (entry-level)',
    'talent acquisition assistant',
    'recruitment coordinator',
    'hr intern',
    'hr trainee',
    'junior hr specialist',
    'hr associate',
    'people operations assistant'
]
location = "New york"